### ISSUE TITLE
whack: Pluto is not running (no "/var/run/pluto/pluto.ctl")

### ISSUE THREAD

**Issue by djoey123** [hwdsl2/docker-ipsec-vpn-server#1] opened 2016-05-28 09:29 UTC
I got this error: whack: Pluto is not running (no "/var/run/pluto/pluto.ctl")

When i check if the server is running how can i fix this?

More error logs of the docker:

```
Trying to auto discover IPs of this server...

================================================
IPsec VPN server is now ready for use!

Connect to your new VPN with these details:

Server IP: ********
IPsec PSK: ********
Username: ********
Password: ********

Write these down. You'll need them to connect!

Setup VPN Clients: https://git.io/vpnclients

================================================

modprobe: ERROR: could not insert 'af_key': Exec format error
Redirecting to: /etc/init.d/ipsec start
Starting pluto IKE daemon for IPsec: Initializing NSS database
.....
xl2tpd[1]: setsockopt recvref[30]: Protocol not available
xl2tpd[1]: This binary does not support kernel L2TP.
xl2tpd[1]: xl2tpd version xl2tpd-1.3.6 started on 87c976415d30 PID:1
xl2tpd[1]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
xl2tpd[1]: Forked by Scott Balmos and David Stipp, (C) 2001
xl2tpd[1]: Inherited by Jeff McAdams, (C) 2002
xl2tpd[1]: Forked again by Xelerance (www.xelerance.com) (C) 2006
xl2tpd[1]: Listening on IP address 0.0.0.0, port 1701
xl2tpd[1]: death_handler: Fatal signal 15 received
```

**Comment by hwdsl2** [comment] 2016-05-28 13:15
@djoey123 Please provide more info about your system, is it on Linux, Mac or Windows? If Linux, which distribution and version? Post the output of "uname -a".

Can you also try the following: On the host, run "sudo modprobe af_key", then "docker restart ipsec-vpn-server". See if this solves the problem.

**Comment by hwdsl2** [comment] 2016-05-28 13:30
@djoey123 A user on the Proxmox forum had a similar issue [1], which was caused by not rebooting the server after a recent kernel upgrade. 

Please try rebooting the host system and start the container again with "docker start ipsec-vpn-server".

[1] https://forum.proxmox.com/threads/error-could-not-insert-iptable_nat-exec-format-error.21802/

**Comment by djoey123** [comment] 2016-05-28 13:50
It didn`t help,
Info: Fedora 23 Server
Linux localhost.localdomain 4.2.3-300.fc23.x86_64 #1 SMP Mon Oct 5 15:42:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hwdsl2** [comment] 2016-05-28 14:14
@djoey123 Please run these commands on the host and post the output:

```
sudo modprobe af_key
sudo dmesg | tail
```

**Comment by djoey123** [comment] 2016-05-28 14:48
[root@localhost ~]# sudo modprobe af_key
[root@localhost ~]# sudo dmesg | tail
[   46.910473] docker0: port 1(veth22fb824) entered forwarding state
[   46.910478] docker0: port 1(veth22fb824) entered forwarding state
[   46.910974] docker0: port 1(veth22fb824) entered disabled state
[   47.052109] eth0: renamed from vetha5c691f
[   47.063962] IPv6: ADDRCONF(NETDEV_CHANGE): veth22fb824: link becomes ready
[   47.063974] docker0: port 1(veth22fb824) entered forwarding state
[   47.063978] docker0: port 1(veth22fb824) entered forwarding state
[   47.063991] IPv6: ADDRCONF(NETDEV_CHANGE): docker0: link becomes ready
[   62.085990] docker0: port 1(veth22fb824) entered forwarding state
[ 3643.884283] NET: Registered protocol family 15

**Comment by hwdsl2** [comment] 2016-05-28 14:50
@djoey123 Thanks for the info. It seems the `af_key` module successfully loaded on the host. Did you try starting the container again?

```
docker stop ipsec-vpn-server
docker start ipsec-vpn-server
[wait 30 seconds]
docker exec -it ipsec-vpn-server ipsec status
```

**Comment by hwdsl2** [comment] 2016-05-28 15:10
@djoey123 OK I just successfully reproduced the issue you had on a Fedora 23 system myself. However after running "sudo modprobe af_key" on the host, the container now runs fine without issues. I'll add the modprobe step to the README to let others know. Thanks for reporting this issue!

If the issue is resolved feel free to close it.

**Comment by djoey123** [comment] 2016-05-28 16:33
I got still this problem
`IPsec VPN server is now ready for use!
Connect to your new VPN with these details:
Server IP: 5.196.250.107
IPsec PSK: vpn_ipsec_psk_test
Username: vpn_user_test
Password: vpn_password_test
Write these down. You'll need them to connect!
Setup VPN Clients: https://git.io/vpnclients
================================================
Redirecting to: /etc/init.d/ipsec start
Starting pluto IKE daemon for IPsec: 
xl2tpd[1]: setsockopt recvref[30]: Protocol not available
xl2tpd[1]: This binary does not support kernel L2TP.
xl2tpd[1]: xl2tpd version xl2tpd-1.3.6 started on d4acd530c7a1 PID:1
xl2tpd[1]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
xl2tpd[1]: Forked by Scott Balmos and David Stipp, (C) 2001
xl2tpd[1]: Inherited by Jeff McAdams, (C) 2002
xl2tpd[1]: Forked again by Xelerance (www.xelerance.com) (C) 2006
xl2tpd[1]: Listening on IP address 0.0.0.0, port 1701`

**Comment by hwdsl2** [comment] 2016-05-28 16:36
@djoey123 The new output looks fine. Please ignore the xl2tpd messages, they are normal.

Which VPN client are you using? Did you follow the configuration steps at https://git.io/vpnclients ?

**Comment by djoey123** [comment] 2016-05-28 19:56
It looks like it cant connect to the port of the server. And yes i followed everythinh

**Comment by hwdsl2** [comment] 2016-05-28 20:19
Please check the docker logs and connect using the credentials shown in the output. Did you see any error message?

**Comment by djoey123** [comment] 2016-05-28 21:21
Nope only the log what i have send u before. No connection logs or something

**Comment by hwdsl2** [comment] 2016-05-28 21:43
Are you using Windows, Mac, Android or iOS as the VPN client? Please double check and re-enter the VPN credentials (I think you used the ones ending in _test). Do you see any error message on the VPN client itself?

**Comment by djoey123** [comment] 2016-05-28 22:20
I use windows as vpn client.
When i try to connect the container with
Docker attach nameofthecontainer
I got the error: death_handler: Fatal signal 2 received.
After that error the container stops working

**Comment by hwdsl2** [comment] 2016-05-28 22:24
Please restart the container with "docker start ipsec-vpn-server". Do not attach to it at this time. Try connecting again from Windows. Do you see any error? e.g. Error 809, Error 628, etc.

**Comment by djoey123** [comment] 2016-05-29 07:46
Its working now i dont know what the problem was... 
I got 1 other question how can i add more users in the server?

**Comment by hwdsl2** [comment] 2016-05-29 14:49
@djoey123 Glad to hear it is working. And thanks for the suggestion about passwords.

To add more users, first get a shell inside the container:

```
docker exec -it ipsec-vpn-server /bin/bash
```

Then edit `/etc/ppp/chap-secrets` (for IPsec/L2TP) and `/etc/ipsec.d/passwd` (for IPsec/XAuth) in the container:

```
export TERM=xterm
nano /etc/ppp/chap-secrets
nano /etc/ipsec.d/passwd
```

Please refer to [1] for the format of those files. When finished, `exit` the container. Then restart it:

```
docker restart ipsec-vpn-server
```

Closing this issue as it is now working. You can continue to comment if needed.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#manage-vpn-users

**Closed by hwdsl2** 2016-05-29 14:49 UTC
