### ISSUE TITLE
TP-Link WAR302 router can't connect to VPN server

### ISSUE THREAD

**Issue by jszsj** [hwdsl2/docker-ipsec-vpn-server#90] opened 2018-09-29 09:52 UTC
the log is:
Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: responding to Main Mode from unknown peer 49.74.32.77 on port 1816
Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: Oakley Transform [3DES_CBC (192), HMAC_MD5, MODP1024] refused
Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: Oakley Transform [3DES_CBC (192), HMAC_SHA1, MODP1024] refused
Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: no acceptable Oakley Transform
Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: sending notification NO_PROPOSAL_CHOSEN to 49.74.32.77:1816
Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: deleting state (STATE_MAIN_R0)
Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77: deleting connection "l2tp-psk"[18] 49.74.32.77 instance with peer 49.74.32.77 {isakmp=#0/ipsec=#0}

How to fix this, thanks!

**Comment by hwdsl2** [comment] 2018-09-30 22:28
Duplicate of https://github.com/hwdsl2/setup-ipsec-vpn/issues/454.

**Closed by hwdsl2** 2018-09-30 22:28 UTC
